# Generated by Django 5.1.5 on 2025-01-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediabook', '0003_remove_userprofile_profileimg_user_profileimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profileimg',
            field=models.ImageField(default='blank=profile', upload_to='UserProfiles/%Y/%m'),
        ),
    ]
